
#ifndef LED_MATRIX__CONFIG_H_
#define LED_MATRIX__CONFIG_H_

#define LEDMX_R0  GPIOA,PIN0
#define LEDMX_R1  GPIOA,PIN1
#define LEDMX_R2  GPIOA,PIN2
#define LEDMX_R3  GPIOA,PIN3
#define LEDMX_R4  GPIOA,PIN4
#define LEDMX_R5  GPIOA,PIN5
#define LEDMX_R6  GPIOA,PIN6
#define LEDMX_R7  GPIOA,PIN7


#define LEDMX_C0  GPIOB,PIN0
#define LEDMX_C1  GPIOB,PIN1
#define LEDMX_C2  GPIOB,PIN2
#define LEDMX_C3  GPIOB,PIN3
#define LEDMX_C4  GPIOB,PIN4
#define LEDMX_C5  GPIOB,PIN5
#define LEDMX_C6  GPIOB,PIN6
#define LEDMX_C7  GPIOB,PIN7

#endif /* LED_MATRIX__CONFIG_H_ */
