
#ifndef GPIO_CONFIGURATIONS_H_
#define GPIO_CONFIGURATIONS_H_
/*
 * Mode			 GPIO_INPUT, GPIO_OUTPUT, GPIO_AF, GPIO_ANALOG
 * Output Mode	 GPIO_PUSH_PULL, GPIO_OPEN_DRAIN, GPIO_Output_NA
 * Speed		 GPIO_LOW_SPEED, GPIO_MEDIUM_SPEED, GPIO_HIGH_SPEED, GPIO_VERY_HIGH_SPEED, GPIO_SPEED_NA
 * Alternate	 choose from Alternate Enum, by default GPIO_AF_NA
 */

#define GPIOA_PIN0_MODE			GPIO_OUTPUT
#define GPIOA_PIN0_OUTPUT_MODE  GPIO_PUSH_PULL
#define GPIOA_PIN0_SPEED		GPIO_MEDIUM_SPEED
#define GPIOA_PIN0_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN1_MODE			GPIO_INPUT
#define GPIOA_PIN1_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN1_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN1_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN2_MODE			GPIO_INPUT
#define GPIOA_PIN2_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN2_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN2_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN3_MODE			GPIO_INPUT
#define GPIOA_PIN3_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN3_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN3_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN4_MODE			GPIO_INPUT
#define GPIOA_PIN4_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN4_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN4_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN5_MODE			GPIO_INPUT
#define GPIOA_PIN5_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN5_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN5_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN6_MODE			GPIO_INPUT
#define GPIOA_PIN6_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN6_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN6_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN7_MODE			GPIO_INPUT
#define GPIOA_PIN7_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN7_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN7_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN8_MODE			GPIO_INPUT
#define GPIOA_PIN8_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN8_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN8_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN9_MODE			GPIO_INPUT
#define GPIOA_PIN9_OUTPUT_MODE  GPIO_Output_NA
#define GPIOA_PIN9_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN9_ALTERNATE    GPIO_AF_NA

#define GPIOA_PIN10_MODE		GPIO_INPUT
#define GPIOA_PIN10_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN10_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN10_ALTERNATE   GPIO_AF_NA

#define GPIOA_PIN11_MODE		GPIO_INPUT
#define GPIOA_PIN11_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN11_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN11_ALTERNATE   GPIO_AF_NA

#define GPIOA_PIN12_MODE		GPIO_INPUT
#define GPIOA_PIN12_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN12_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN12_ALTERNATE   GPIO_AF_NA

#define GPIOA_PIN13_MODE		GPIO_ANALOG
#define GPIOA_PIN13_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN13_SPEED		GPIO_VERY_HIGH_SPEED
#define GPIOA_PIN13_ALTERNATE   GPIO_AF_NA

#define GPIOA_PIN14_MODE		GPIO_INPUT
#define GPIOA_PIN14_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN14_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN14_ALTERNATE   GPIO_AF_NA

#define GPIOA_PIN15_MODE		GPIO_INPUT
#define GPIOA_PIN15_OUTPUT_MODE GPIO_Output_NA
#define GPIOA_PIN15_SPEED		GPIO_SPEED_NA
#define GPIOA_PIN15_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN0_MODE			GPIO_INPUT
#define GPIOB_PIN0_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN0_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN0_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN1_MODE			GPIO_INPUT
#define GPIOB_PIN1_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN1_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN1_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN2_MODE			GPIO_INPUT
#define GPIOB_PIN2_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN2_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN2_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN3_MODE			GPIO_AF
#define GPIOB_PIN3_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN3_SPEED		GPIO_VERY_HIGH_SPEED
#define GPIOB_PIN3_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN4_MODE			GPIO_AF
#define GPIOB_PIN4_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN4_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN4_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN5_MODE			GPIO_INPUT
#define GPIOB_PIN5_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN5_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN5_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN6_MODE			GPIO_INPUT
#define GPIOB_PIN6_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN6_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN6_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN7_MODE			GPIO_INPUT
#define GPIOB_PIN7_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN7_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN7_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN8_MODE			GPIO_INPUT
#define GPIOB_PIN8_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN8_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN8_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN9_MODE			GPIO_INPUT
#define GPIOB_PIN9_OUTPUT_MODE  GPIO_Output_NA
#define GPIOB_PIN9_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN9_ALTERNATE    GPIO_AF_NA

#define GPIOB_PIN10_MODE		GPIO_INPUT
#define GPIOB_PIN10_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN10_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN10_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN11_MODE		GPIO_INPUT
#define GPIOB_PIN11_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN11_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN11_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN12_MODE		GPIO_INPUT
#define GPIOB_PIN12_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN12_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN12_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN13_MODE		GPIO_INPUT
#define GPIOB_PIN13_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN13_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN13_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN14_MODE		GPIO_INPUT
#define GPIOB_PIN14_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN14_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN14_ALTERNATE   GPIO_AF_NA

#define GPIOB_PIN15_MODE		GPIO_INPUT
#define GPIOB_PIN15_OUTPUT_MODE GPIO_Output_NA
#define GPIOB_PIN15_SPEED		GPIO_SPEED_NA
#define GPIOB_PIN15_ALTERNATE   GPIO_AF_NA
#endif /* GPIO_CONFIGURATIONS_H_ */
